//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Web_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Cold
    {
        public int Tab8_ID { get; set; }
        public Nullable<bool> Heat_status_cold { get; set; }
        public Nullable<bool> Win_ins_status_cold { get; set; }
        public int Room_temp_cold { get; set; }
        public Nullable<bool> duct_status_cold { get; set; }
        public Nullable<bool> caulk_status_cold { get; set; }
    }
}
