//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Web_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_wisdom
    {
        public int Tab_wisdom_ID { get; set; }
        public int time { get; set; }
        public Nullable<int> hint_counter { get; set; }
        public Nullable<int> object_counter { get; set; }
        public int score { get; set; }
    }
}
