//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Web_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2
    {
        public int Tab2_ID { get; set; }
        public int Room_temp_Heat { get; set; }
        public byte[] AC_status_heat { get; set; }
        public byte[] Window_status_heat { get; set; }
        public byte[] Blinds_status_heat { get; set; }
        public byte[] Fan_status_heat { get; set; }
    }
}
