//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Web_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_9
    {
        public int Tab9_ID { get; set; }
        public int Room_temp_bill { get; set; }
        public Nullable<bool> heat_status_bill { get; set; }
        public Nullable<bool> Window_status_bill { get; set; }
        public Nullable<bool> ducts_status_bill { get; set; }
        public Nullable<bool> caulking_status_bill { get; set; }
    }
}
