//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Web_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int TabId_ID { get; set; }
        public Nullable<bool> AC_status { get; set; }
        public Nullable<bool> Window_status { get; set; }
        public Nullable<int> Room_temp_Page4 { get; set; }
    }
}
