//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Web_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_7
    {
        public int tab7_ID { get; set; }
        public int room_temp_7 { get; set; }
    }
}
